### ISSUE TITLE
Upgrade to version 5.x

### ISSUE THREAD

**Issue by agamm** [render-examples/ghost#7]
I managed to upgrade this template to 5.x, I opened the issue to check if you want me to create  a PR for that.

**Comment by starascendin** [comment]
@agamm can you share how you did the migration? I'm also looking to upgrade and it'll be good to learn from/follow your exp!

**Comment by bradybellini** [comment]
You should just submit a PR or create your own repo, as I am also interested in updating to the latest version of ghost on render.
